SEL/SEL/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SEL.Models;
using SEL.DAL;

namespace SEL.Controllers
{   
    public class MessageController : Controller
    {
        private SelContext context = new SelContext();

        //
        // GET: /Message/

        public ViewResult Index()
        {
            List<Message> messages= new List<Message>();
            User user = Session["login"] as User;
            return View(context.Message.Where(m=>m.destID==user.ID).ToList());
        }

        //
        // GET: /Message/Details/5

        public ViewResult Details(int id)
        {
            Message message = context.Message.Single(x => x.ID == id);
            @ViewBag.ownerPseudo = context.User.Find(message.senderID).pseudo;
            return View(message);
        }

        //
        // GET: /Message/Create

        public ActionResult Create()
        {
            ViewBag.Possiblesender = context.User;
            ViewBag.Possibledest = context.User;
            var tmp = context.Set<User>().ToArray();
            List<string> users = new List<string>();
            foreach (User u in tmp)
            {
                users.Add(u.pseudo);
            }
            ViewBag.nameUsers = users;
            ViewBag.destUserPseudo=Request.QueryString["destUserPseudo"];
            return View();
        } 
        //
        // POST: /Message/Create

        [HttpPost]
        public ActionResult Create(Message msg,string dest)
        {
            User destUser = context.User.Where(m=>m.pseudo==dest).First();
            User user = Session["login"] as User;
            msg.senderID = user.ID;
            msg.destID = destUser.ID;
            if(msg.title !=null && msg.message!=null && msg.senderID !=0 && msg.destID!= 0)
            {
                context.Message.Add(msg);
                context.SaveChanges();
                return RedirectToAction("Index"); 
            }
 
            /*if (ModelState.IsValid)
            {
                context.Message.Add(msg);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }*/
            
            ViewBag.Possiblesender = context.User;
            ViewBag.Possibledest = context.User;
            return View(msg);
        }
        
        //
        // GET: /Message/Edit/5
 
        public ActionResult Edit(int id)
        {
            Message message = context.Message.Single(x => x.ID == id);
            ViewBag.Possiblesender = context.User;
            ViewBag.Possibledest = context.User;
            return View(message);
        }

        //
        // POST: /Message/Edit/5

        [HttpPost]
        public ActionResult Edit(Message msg)
        {
            if (ModelState.IsValid)
            {
                context.Entry(msg).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Possiblesender = context.User;
            ViewBag.Possibledest = context.User;
            return View(msg);
        }

        //
        // GET: /Message/Delete/5
 
        public ActionResult Delete(int id)
        {
            Message message = context.Message.Single(x => x.ID == id);
            return View(message);
        }

        //
        // POST: /Message/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = context.Message.Single(x => x.ID == id);
            context.Message.Remove(message);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

SEL/SEL/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SEL.Models;
using SEL.DAL;
using System.Data.Entity.SqlServer;
using System.IO;

namespace SEL.Controllers
{
    public class OfferController : Controller
    {
        private SelContext context = new SelContext();

        //
        // GET: /Offer/

        public ViewResult Index()
        {
            List<Offer> offers = context.Offer.ToList();
            List<Offer> validOffers = new List<Offer>();
            foreach (Offer o in offers)
            {
                DateTime dt = o.endDate;
                if (DateTime.Compare(DateTime.Now,dt)<0)
                {
                    validOffers.Add(o);
                }

            }
            return View(validOffers);
            //return View(context.Offer.Include(offer => offer.owner).Include(offer => offer.tag).ToList());
        }

        //
        // GET: /Offer/Details/5

        public ViewResult Details(int id)
        {
            Offer offer = context.Offer.Single(x => x.ID == id);
            @ViewBag.ownerPseudo = context.User.Find(offer.ownerID).pseudo;
            List<OfferTag> otList = context.OfferTag.Where(m=>m.offerID==offer.ID).ToList();
            List<string> tagName = new List<string>();
            foreach(OfferTag ot in otList)
            {
                tagName.Add(context.Tag.Find(ot.tagID).tag);
            }
            @ViewBag.tagList = tagName;
            return View(offer);
        }
        
        //
        // GET: /Offer/Create

        public ActionResult Create()
        {
            ViewBag.Possibleowner = context.User;
            ViewBag.tagList = context.Tag.ToList().Select(m=>m.tag);
            return View();
        }

        //
        // POST: /Offer/Create

        [HttpPost]
        public ActionResult Create(Offer offer, string[] tagList, HttpPostedFileBase file)
        {
            User user = Session["login"] as User;
            offer.ownerID = user.ID;
            if (file != null)
            {
                string filePath = Path.Combine(Server.MapPath("~/img/"), Path.GetFileName(file.FileName));
                file.SaveAs(filePath);
                offer.picture = "~/img/" + file.FileName;

            }
            else
            {
                offer.picture = "~/img/gift.png";
            }

            if (ModelState.IsValid)
            {

                context.Offer.Add(offer);
                context.SaveChanges();
                foreach (string strTag in tagList)
                {
                    if(strTag!="")
                    { 
                        Tag tag = context.Tag.Where(m => m.tag == strTag).First();
                        OfferTag newEntry = new OfferTag();
                        newEntry.tagID = tag.ID;
                        newEntry.offerID = offer.ID;
                        context.OfferTag.Add(newEntry);
                        context.SaveChanges();
                    }
                }
                
                return RedirectToAction("Index");  
            }

            ViewBag.Possibleowner = context.User;
            return View(offer);
        }

        //
        // GET: /Offer/Edit/5

        public ActionResult Edit(int id)
        {
            Offer offer = context.Offer.Single(x => x.ID == id);
            ViewBag.Possibleowner = context.User;
            ViewBag.tagList = context.Tag.ToList().Select(m => m.tag);
            List<OfferTag> otList = context.OfferTag.Where(m => m.offerID == offer.ID).ToList();
            List<string> tagName = new List<string>();
            foreach (OfferTag ot in otList)
            {
                tagName.Add(context.Tag.Find(ot.tagID).tag);
            }
            @ViewBag.offerTags = tagName;
            return View(offer);
        }

        //
        // POST: /Offer/Edit/5

        [HttpPost]
        public ActionResult Edit(Offer offer, string[] tagList, HttpPostedFileBase file)
        {
            if (file != null)
            {
                string filePath = Path.Combine(Server.MapPath("~/img/"), Path.GetFileName(file.FileName));
                file.SaveAs(filePath);
                offer.picture = "~/img/" + file.FileName;

            }
            
            User user = Session["login"] as User;
            offer.ownerID = user.ID;
            if (ModelState.IsValid)
            {
                context.Entry(offer).State = EntityState.Modified;
                context.SaveChanges();

                //remove existing tags
                List<OfferTag> ot = context.OfferTag.Where(m => m.offerID == offer.ID).ToList();
                foreach (OfferTag offerToDelete in ot)
                {
                    context.OfferTag.Remove(offerToDelete);
                    context.SaveChanges();
                }

                //add new tags
                foreach (string strTag in tagList)
                {
                    if (strTag != "")
                    {
                        Tag tag = context.Tag.Where(m => m.tag == strTag).First();
                        OfferTag newEntry = new OfferTag();
                        newEntry.tagID = tag.ID;
                        newEntry.offerID = offer.ID;
                        context.OfferTag.Add(newEntry);
                        context.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.Possibleowner = context.User;
            ViewBag.tagList = context.Tag.ToList().Select(m => m.tag);
            List<OfferTag> otList = context.OfferTag.Where(m => m.offerID == offer.ID).ToList();
            List<string> tagName = new List<string>();
            foreach (OfferTag ot in otList)
            {
                tagName.Add(context.Tag.Find(ot.tagID).tag);
            }
            @ViewBag.offerTags = tagName;
            return View(offer);
        }

        //
        // GET: /Offer/Delete/5

        public ActionResult Delete(int id)
        {
            Offer offer = context.Offer.Single(x => x.ID == id);
            return View(offer);
        }

        //
        // POST: /Offer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Offer offer = context.Offer.Single(x => x.ID == id);
            context.OfferTag.RemoveRange(offer.tag);
            context.Offer.Remove(offer);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Search(string search)
        {
            List<Offer> offersSearch = context.Offer.Where(o => o.description.Contains(search) || o.name.Contains(search)).ToList();
            List<OfferTag> offersSearchTags = context.OfferTag.Where(ot => ot.tag.tag.Contains(search)).ToList();
            foreach(OfferTag ot in offersSearchTags)
            {
                if(!offersSearch.Contains(ot.offer))
                {
                    offersSearch.Add(ot.offer);
                }
                
            }
            return View(offersSearch);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SEL/SEL/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SEL.Models;
using SEL.DAL;
using System.Security.Cryptography;
using System.Text;
using System.Web.Security;

namespace SEL.Controllers
{   
    public class UserController : Controller
    {
        private SelContext context = new SelContext();

        //
        // GET: /User/

        public ViewResult Index()
        {
            return View(context.User.ToList());
        }

        //
        // GET: /User/Details/5

        public ViewResult Details(int id)
        {
            User user = context.User.Single(x => x.ID == id);
            return View(user);
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /User/Create

        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            
            {
                user.password = FormsAuthentication.HashPasswordForStoringInConfigFile(user.password,"SHA1");
                context.User.Add(user);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }
        
        //
        // GET: /User/Edit/5
 
        public ActionResult Edit(int id)
        {
            User user = context.User.Single(x => x.ID == id);
            return View(user);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                context.Entry(user).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        //
        // GET: /User/Delete/5
 
        public ActionResult Delete(int id)
        {
            User user = context.User.Single(x => x.ID == id);
            return View(user);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = context.User.Single(x => x.ID == id);
            List<Offer> offersToDelete = context.Offer.Where(m => m.ownerID == user.ID).ToList();
            foreach (Offer o in offersToDelete)
            {
                context.OfferTag.RemoveRange(o.tag);
            }
            context.SaveChanges();
            foreach (Offer o in context.Offer.Where(m => m.ownerID == user.ID))
            {
                context.Offer.Remove(o);
            }
            foreach (Message msg in context.Message.Where(m => m.senderID == user.ID || m.destID == user.ID))
            {
                context.Message.Remove(msg);
            }
            context.User.Remove(user);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }

        
       
    }
}

SEL/SEL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="@Url.Action("Index", "Home")"><img src="~/img/sel.png" alt="image" class="logo" /></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Offers", "Index", "Offer")</li>
                        <li>@Html.ActionLink("Users", "Index", "User")</li>
                        @if (Session["login"] != null)
                        {
                            SEL.Models.User current = (SEL.Models.User)HttpContext.Current.Session["login"];
                            <li>@Html.ActionLink("Messages", "Index", "Message")</li>                      
                            <li>@Html.ActionLink("Me", "Details", "User", new { id = current.ID }, null)</li>

                        }
                    </ul>
                    <div class="navbar-right">
                        @if (Session["login"] == null)
                        {
                            <ul class="nav pull-right">
                                <li class="dropdown" id="menuLogin">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">Login</a>
                                    <div class="dropdown-menu" style="padding:17px;">
                                        @Html.Partial("_login")
                                    </div>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <div style="padding:17px;">
                                @Html.ActionLink("Logout", "Logout", "Home")
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            @RenderBody()
            </div>
        </div>
    <div class="footer">
        <footer>

            <div class="container">
                <p style="padding: 20px">&copy; @DateTime.Now.Year - Lucien Moor, Léa von Muralt</p>
            </div>
        </footer>
   </div>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

SEL/SEL/Views/Shared/_login.cshtml
@{Html.BeginForm("Login", "Home", new {@class="navbar-form", @role="search" });}
    <div class="form-group">
        @Html.TextBox("email", "", new { @placeholder = "email", @class="form-control"})
    </div>
    <div class="form-group">
        @Html.Password("password", "", new { @placeholder = "password", @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default" style="align-content: center;">Login</button>
    <br />
    <div class="text-center">
        @Html.Label("Or ")
        @Html.ActionLink("Sign up!", "Create", "User")
    </div>

@{Html.EndForm();}